from __future__ import annotations

import csv
import json
import shutil
import subprocess
from pathlib import Path
from types import SimpleNamespace
from typing import Any

from .dataset import utc_now
from .errors import CliError, EXIT_DATASET_MISSING, EXIT_OUTPUT_INVALID, EXIT_SEQUENCE_ARTIFACT_MISSING, EXIT_SEQUENCE_RUNNER_FAILED, EXIT_USAGE
from .schema import ClassSchema
from .validate_sequence import compare_sequence_event_decisions, _load_event_decisions


def _resolve_existing_path(raw: str, name: str, *, directory: bool | None = None) -> Path:
    path = Path(raw).expanduser().resolve()
    if not path.exists():
        raise CliError("SEQUENCE_INPUT_MISSING", f"{name} path does not exist.", EXIT_DATASET_MISSING, {"path": str(path)}, "validate-sequence")
    if directory is True and not path.is_dir():
        raise CliError("SEQUENCE_INPUT_INVALID", f"{name} path must be a directory.", EXIT_USAGE, {"path": str(path)}, "validate-sequence")
    if directory is False and not path.is_file():
        raise CliError("SEQUENCE_INPUT_INVALID", f"{name} path must be a file.", EXIT_USAGE, {"path": str(path)}, "validate-sequence")
    return path


def _relative_or_absolute(path: Path, root: Path) -> str:
    try:
        return str(path.relative_to(root))
    except ValueError:
        return str(path)


def _copy_or_generate_detector_settings(args: Any, destination: Path) -> tuple[str, list[dict[str, Any]]]:
    warnings: list[dict[str, Any]] = []
    if getattr(args, "detector_settings", None):
        source = _resolve_existing_path(args.detector_settings, "detector settings", directory=False)
        shutil.copyfile(source, destination)
        return str(destination), warnings

    payload = {
        "schema_version": "validator.detector-settings-snapshot.v1",
        "source": "runtime_defaults_hardcoded",
        "created_at": utc_now(),
        "settings": {
            "save_crop": True,
            "save_overlay": False,
            "crop_size": 64,
            "frame_skip": 0,
            "bg_frames": 100,
            "bg_update_frames": 50,
            "reset_frames": 2,
            "min_area": -1.0,
            "min_area_frac": 0.0,
            "max_area_frac": 0.10,
            "min_bbox": 32,
            "margin": 5,
            "diff_thresh": 15,
            "blur_radius": 1,
            "morph_radius": 1,
            "scale": 0.5,
            "gap_fire_shift": 0,
            "use_contour_extraction": False,
        },
        "limitations": [
            "Generated by validator wrapper from the current sequence_headless defaults.",
            "Promotion-quality reproducibility remains blocked until runtime exports or accepts versioned detector settings.",
        ],
    }
    destination.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    warnings.append(
        {
            "code": "DETECTOR_SETTINGS_GENERATED_FROM_RUNTIME_DEFAULTS",
            "message": "No --detector-settings file was supplied; validator wrote a snapshot of current hardcoded sequence_headless defaults.",
            "details": {"detector_settings_path": str(destination)},
        }
    )
    return str(destination), warnings


def _copy_optional_file(raw: str | None, destination: Path) -> str | None:
    if not raw:
        return None
    source = _resolve_existing_path(raw, destination.name, directory=False)
    shutil.copyfile(source, destination)
    return str(destination)


def _find_latest_runner_output(raw_output_base: Path) -> Path:
    children = [path for path in raw_output_base.iterdir() if path.is_dir() and path.name.startswith("sequence_")]
    if not children:
        raise CliError(
            "SEQUENCE_RUNNER_ARTIFACTS_MISSING",
            "Sequence runner completed but did not create a sequence_<timestamp> output directory.",
            EXIT_SEQUENCE_ARTIFACT_MISSING,
            {"raw_output_base": str(raw_output_base)},
            "validate-sequence",
        )
    return max(children, key=lambda path: path.stat().st_mtime)


def _single_artifact(raw_output_dir: Path, pattern: str, code: str) -> Path:
    matches = sorted(raw_output_dir.glob(pattern))
    if not matches:
        raise CliError(
            code,
            f"Required runner artifact matching {pattern} was not found.",
            EXIT_SEQUENCE_ARTIFACT_MISSING,
            {"raw_output_dir": str(raw_output_dir), "pattern": pattern},
            "validate-sequence",
        )
    return matches[-1]


def _read_summary_csv(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        return list(csv.DictReader(handle))


def run_validate_sequence_runner(args: Any, schema: ClassSchema) -> tuple[dict[str, Any], int]:
    runner_path = _resolve_existing_path(args.sequence_runner, "sequence runner", directory=False)
    sequence_path = _resolve_existing_path(args.sequence, "sequence", directory=True)
    model_path = _resolve_existing_path(args.model, "model", directory=False)
    metadata_path = _resolve_existing_path(args.metadata, "metadata", directory=False)
    output_root = Path(args.output).expanduser().resolve()
    sequence_dir = output_root / "sequence_validation"
    logs_dir = output_root / "logs"
    raw_output_base = sequence_dir / "raw_sequence_headless"
    sequence_dir.mkdir(parents=True, exist_ok=True)
    logs_dir.mkdir(parents=True, exist_ok=True)
    raw_output_base.mkdir(parents=True, exist_ok=True)

    try:
        fps = float(args.fps)
    except (TypeError, ValueError):
        raise CliError("SEQUENCE_FPS_INVALID", "--fps must be a positive number.", EXIT_USAGE, {"fps": args.fps}, "validate-sequence")
    if fps <= 0:
        raise CliError("SEQUENCE_FPS_INVALID", "--fps must be a positive number.", EXIT_USAGE, {"fps": args.fps}, "validate-sequence")

    detector_settings_path, warnings = _copy_or_generate_detector_settings(args, sequence_dir / "detector_settings_snapshot.json")
    settings_snapshot_path = _copy_optional_file(getattr(args, "settings_snapshot", None), sequence_dir / "runtime_settings_snapshot.json")

    command = [
        str(runner_path),
        "--input",
        str(sequence_path),
        "--fps",
        str(args.fps),
        "--output",
        str(raw_output_base),
        "--onnx",
        str(model_path),
        "--metadata",
        str(metadata_path),
        "--target-class-id",
        str(args.target_class_id),
        "--provider",
        str(getattr(args, "provider", None) or "cpu"),
        "--batch-size",
        str(getattr(args, "batch_size", None) if getattr(args, "batch_size", None) is not None else 0),
    ]

    stdout_log = logs_dir / "sequence_headless_stdout.log"
    stderr_log = logs_dir / "sequence_headless_stderr.log"
    with stdout_log.open("w", encoding="utf-8") as stdout_handle, stderr_log.open("w", encoding="utf-8") as stderr_handle:
        completed = subprocess.run(command, stdout=stdout_handle, stderr=stderr_handle, cwd=str(output_root), check=False)

    if completed.returncode != 0:
        artifacts = {
            "schema_version": "validator.v1",
            "runner": {
                "path": str(runner_path),
                "command": command,
                "exit_code": completed.returncode,
                "stdout_log": _relative_or_absolute(stdout_log, output_root),
                "stderr_log": _relative_or_absolute(stderr_log, output_root),
            },
            "inputs": {
                "sequence_path": str(sequence_path),
                "fps": fps,
                "model_path": str(model_path),
                "metadata_path": str(metadata_path),
                "target_class_id": str(args.target_class_id),
                "detector_settings_path": _relative_or_absolute(Path(detector_settings_path), output_root),
                "settings_snapshot_path": _relative_or_absolute(Path(settings_snapshot_path), output_root) if settings_snapshot_path else None,
            },
            "raw_output": {},
            "warnings": warnings,
            "errors": [{"code": "SEQUENCE_RUNNER_FAILED", "message": "Sequence runner exited non-zero."}],
        }
        artifacts_path = sequence_dir / "sequence_artifacts.json"
        artifacts_path.write_text(json.dumps(artifacts, indent=2), encoding="utf-8")
        raise CliError(
            "SEQUENCE_RUNNER_FAILED",
            "Sequence runner exited non-zero.",
            EXIT_SEQUENCE_RUNNER_FAILED,
            {"exit_code": completed.returncode, "stdout_log": str(stdout_log), "stderr_log": str(stderr_log), "sequence_artifacts": str(artifacts_path)},
            "validate-sequence",
        )

    raw_output_dir = _find_latest_runner_output(raw_output_base)
    per_frame_csv = _single_artifact(raw_output_dir, "sequence_test_log_*.csv", "SEQUENCE_TEST_LOG_MISSING")
    event_trajectory_csv = _single_artifact(raw_output_dir, "sequence_event_trajectory_*.csv", "SEQUENCE_EVENT_TRAJECTORY_MISSING")
    event_decisions_csv = _single_artifact(raw_output_dir, "sequence_event_decisions_*.csv", "SEQUENCE_EVENT_DECISIONS_MISSING")
    summary_csv = _single_artifact(raw_output_dir, "sequence_summary_*.csv", "SEQUENCE_SUMMARY_MISSING")

    runtime_rows, runtime_warnings = _load_event_decisions(event_decisions_csv, schema)
    warnings.extend(runtime_warnings)
    runner_summary_rows = _read_summary_csv(summary_csv)

    artifacts_path = sequence_dir / "sequence_artifacts.json"
    artifacts = {
        "schema_version": "validator.v1",
        "runner": {
            "path": str(runner_path),
            "command": command,
            "exit_code": completed.returncode,
            "stdout_log": _relative_or_absolute(stdout_log, output_root),
            "stderr_log": _relative_or_absolute(stderr_log, output_root),
        },
        "inputs": {
            "sequence_path": str(sequence_path),
            "fps": fps,
            "model_path": str(model_path),
            "metadata_path": str(metadata_path),
            "target_class_id": str(args.target_class_id),
            "provider": str(getattr(args, "provider", None) or "cpu"),
            "batch_size": int(getattr(args, "batch_size", None) if getattr(args, "batch_size", None) is not None else 0),
            "detector_settings_path": _relative_or_absolute(Path(detector_settings_path), output_root),
            "settings_snapshot_path": _relative_or_absolute(Path(settings_snapshot_path), output_root) if settings_snapshot_path else None,
            "ground_truth_path": str(Path(args.ground_truth).expanduser().resolve()) if getattr(args, "ground_truth", None) else None,
            "review_checklist_path": str(Path(args.review_checklist).expanduser().resolve()) if getattr(args, "review_checklist", None) else None,
        },
        "raw_output": {
            "raw_output_dir": _relative_or_absolute(raw_output_dir, output_root),
            "per_frame_csv": _relative_or_absolute(per_frame_csv, output_root),
            "event_trajectory_csv": _relative_or_absolute(event_trajectory_csv, output_root),
            "event_decisions_csv": _relative_or_absolute(event_decisions_csv, output_root),
            "summary_csv": _relative_or_absolute(summary_csv, output_root),
        },
        "warnings": warnings,
        "errors": [],
    }
    artifacts_path.write_text(json.dumps(artifacts, indent=2), encoding="utf-8")

    run_manifest = {
        "schema_version": "validator.v1",
        "run_id": output_root.name,
        "mode": "sequence",
        "source_mode": "runner_wrapped",
        "created_at": utc_now(),
        "internal_provisional": True,
        "sequence_artifacts": str(artifacts_path),
        "runner": artifacts["runner"],
        "inputs": artifacts["inputs"],
        "raw_output": artifacts["raw_output"],
        "warnings": warnings,
    }
    (output_root / "run_manifest.json").write_text(json.dumps(run_manifest, indent=2), encoding="utf-8")

    if getattr(args, "ground_truth", None):
        compare_args = SimpleNamespace(
            event_decisions=str(event_decisions_csv),
            ground_truth=args.ground_truth,
            review_checklist=getattr(args, "review_checklist", None),
            output=str(output_root),
        )
        payload, exit_code = compare_sequence_event_decisions(
            compare_args,
            schema,
            source_mode="runner_wrapped",
            event_decisions_source="fresh_runner_output",
            extra_sequence_fields={
                "sequence_path": str(sequence_path),
                "runner_path": str(runner_path),
                "raw_output_dir": str(raw_output_dir),
                "sequence_artifacts_path": str(artifacts_path),
            },
            extra_artifacts={"sequence_artifacts_json": str(artifacts_path)},
            extra_warnings=warnings,
        )
        return payload, exit_code

    summary_path = sequence_dir / "sequence_validation_summary.json"
    metrics_path = sequence_dir / "sequence_metrics.csv"
    with metrics_path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=["metric", "value"])
        writer.writeheader()
        writer.writerow({"metric": "runtime_events_total", "value": str(len(runtime_rows))})
        writer.writerow({"metric": "runner_summary_rows", "value": str(len(runner_summary_rows))})

    summary = {
        "schema_version": "validator.v1",
        "run_id": output_root.name,
        "mode": "sequence",
        "status": "completed",
        "created_at": utc_now(),
        "internal_provisional": True,
        "sequence": {
            "source_mode": "runner_wrapped",
            "event_decisions_source": "fresh_runner_output",
            "sequence_path": str(sequence_path),
            "runner_path": str(runner_path),
            "event_decisions_path": str(event_decisions_csv),
            "ground_truth_path": None,
            "review_checklist_path": None,
            "source_sequence_id": runtime_rows[0]["source_sequence_id"] if runtime_rows else None,
            "raw_output_dir": str(raw_output_dir),
            "sequence_artifacts_path": str(artifacts_path),
        },
        "class_schema": {
            "label_schema_version": schema.schema_id,
            "classes": schema.classes,
            "display_labels": schema.display_labels,
        },
        "runtime_metrics": {
            "runtime_events_total": len(runtime_rows),
            "runner_summary_rows": len(runner_summary_rows),
        },
        "ground_truth_metrics": None,
        "adjudicated_ground_truth_metrics": None,
        "review_adjudication": None,
        "artifacts": {
            "sequence_metrics_csv": str(metrics_path),
            "sequence_artifacts_json": str(artifacts_path),
        },
        "warnings": [
            *warnings,
            {
                "code": "SEQUENCE_GROUND_TRUTH_NOT_SUPPLIED",
                "message": "Runner-wrapped validation consumed fresh runner artifacts, but no ground truth was supplied; event-level accuracy metrics were not computed.",
                "details": {},
            },
            {
                "code": "PROVISIONAL_INTERNAL_SEQUENCE_REPLAY",
                "message": "Runner-wrapped sequence validation is internal/provisional and is not promotion-quality sequence accuracy evidence.",
                "details": {},
            },
        ],
        "errors": [],
    }
    summary_path.write_text(json.dumps(summary, indent=2), encoding="utf-8")
    payload = {
        "schema_version": 1,
        "command": "validate-sequence",
        "status": "ok",
        "timestamp": utc_now(),
        "message": "Runner-wrapped sequence replay completed; no ground truth metrics were computed.",
        "summary_path": str(summary_path),
        "runtime_metrics": summary["runtime_metrics"],
        "warnings": summary["warnings"],
        "errors": [],
    }
    return payload, 0
