### This file is automatically generated by Qt Design Studio.
### Do not change

find_package(Qt6 6.8 REQUIRED COMPONENTS QuickControls2)

add_subdirectory(Desktop_app_v2)
add_subdirectory(Desktop_app_v2Content)
add_subdirectory(App)
add_subdirectory(Dependencies)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    Desktop_app_v2plugin
    Desktop_app_v2Contentplugin
    Qt6::Quick
    Qt6::Core
    Qt6::Gui
    Qt6::Qml
    Qt6::QuickControls2
)
